# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gmina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('kod', models.CharField(max_length=10)),
                ('powiat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kandydat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Obwod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.IntegerField()),
                ('nazwa', models.CharField(max_length=200)),
                ('uprawnieni', models.IntegerField(default=0)),
                ('kartyWydane', models.IntegerField(default=0)),
                ('glosyOddane', models.IntegerField(default=0)),
                ('glosyNiewazne', models.IntegerField(default=0)),
                ('glosyWazne', models.IntegerField(default=0)),
                ('gmina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkw.Gmina')),
            ],
        ),
        migrations.CreateModel(
            name='Okreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wojewodztwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wynik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wynik', models.IntegerField(default=0)),
                ('kandydat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkw.Kandydat')),
                ('obwod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkw.Obwod')),
            ],
        ),
        migrations.AddField(
            model_name='okreg',
            name='wojewodztwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkw.Wojewodztwo'),
        ),
        migrations.AddField(
            model_name='obwod',
            name='okreg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkw.Okreg'),
        ),
        migrations.AddField(
            model_name='gmina',
            name='okreg',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pkw.Okreg'),
        ),
    ]
